# Paths
all_video_names: list/all.video
video_path: ../videos
downsampled_videos: ./downsampled_videos #~/11775-hws/hw2_code/downsampled_videos
surf_features: ~/11775-hws/hw2_code/surf

# downsampling
downsampling_frame_len: 60
downsampling_frame_rate: 15
keyframe_interval: 10

# surf
hessian_threshold: 400
kmeans_cluster_num: 256
